# Generated by Django 6.0.2 on 2026-02-08 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=300)),
                ('arrondissement', models.CharField(choices=[('1', '1e'), ('2', '2e'), ('3', '3e'), ('4', '4e'), ('5', '5e'), ('6', '6e'), ('7', '7e'), ('8', '8e'), ('9', '9e'), ('10', '10e'), ('11', '11e'), ('12', '12e'), ('13', '13e'), ('14', '14e'), ('15', '15e'), ('16', '16e'), ('17', '17e'), ('18', '18e'), ('19', '19e'), ('20', '20e')], max_length=2)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hospital', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('generales', 'Urgences générales'), ('pediatriques', 'Urgences pédiatriques'), ('cardiologiques', 'Urgences cardiologiques'), ('psychiatriques', 'Urgences psychiatriques'), ('ophtalmologiques', 'Urgences ophtalmologiques'), ('dentaires', 'Urgences dentaires'), ('gyneco_obstetrique', 'Urgences gynécologiques/obstétriques'), ('orl', 'Urgences ORL'), ('main_traumato', 'Urgences main & traumatologie')], max_length=200)),
                ('is_available', models.BooleanField(default=True)),
                ('queue_count', models.PositiveIntegerField(default=0)),
                ('estimated_wait_time', models.PositiveIntegerField(default=0, help_text="Temps d'attente estimé en minutes")),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='hospitals.hospital')),
            ],
        ),
    ]
